### ISSUE TITLE
Specifying any FaxOptions in the fax.Send causes RuntimeBinderException

### ISSUE THREAD

**Issue by gbanister** [phaxio/phaxio-dotnet#2]
```
var testOptions = new FaxOptions
            {
                HeaderText = "headertext",
                StringData = "somedata",
                StringDataType = "html",
                IsBatch = true,
                BatchDelaySeconds = 10,
                AvoidBatchCollision = true,
                CallbackUrl = "https://example.com/callback",
                CancelTimeoutAfter = 20,
                CallerId = "3213214321",
                FailureErrorType = "failure_type"
            };

            fax.Send(document.Address, file, testOptions);
```

{"Cannot perform runtime binding on a null reference"}

   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Phaxio.PhaxioClient.SendFax(IEnumerable`1 toNumbers, IEnumerable`1 files, FaxOptions options)
   at Phaxio.Entities.Fax.Send(IEnumerable`1 toNumbers, IEnumerable`1 files, FaxOptions options)
   at Phaxio.Entities.Fax.Send(String toNumber, FileInfo file, FaxOptions options)
   at Oviss.EmailSender.Program.SendFax(Documents document) in C:\projects\Oviss.EmailSender\Oviss.EmailSender\Oviss.EmailSender\Program.cs:line 94
   at Oviss.EmailSender.Program.Main(String[] args) in C:\projects\Oviss.EmailSender\Oviss.EmailSender\Oviss.EmailSender\Program.cs:line 55
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

But Send works fine if I don't specify FaxOptions.

**Comment by noelherrick** [comment]
This was fixed in the v1.1 release.
